### ISSUE TITLE
Omit responses from misconfigured service nodes from the "consensus" response set 

### ISSUE THREAD

**Issue by synechist** [blocknetdx/go-xrouter#45]
### Current behaviour
Testing reveals that Go-XRouter is likely including into "consensus" the invalid responses from misconfigured service nodes, in the event that it first makes the request to such a node. 

For example, testing indicates that if a `queryCount` of 1 is set, and if Go-XRouter first makes a request to a misconfigured service node, and then goes on to make the request to a second (correctly configured) service node, then the resulting response set includes one of the responses as `mostCommonReply` and the other as `divergentReply`. 

### Intended behaviour
1. If `queryCount` is _x_ in main.go, then (as per current behaviour) Go-XRouter should only query _x_ correctly configured EXR service nodes.
2. If Go-XRouter receives an invalid response (e.g. "null" or empty response), then (as per current behaviour) it should query additional service nodes until `queryCount` is satisfied or until no further service nodes are available.
3. When compiling the response set for "consensus," it should omit invalid responses.

Suggested types of invalid response:
- null response
- empty `message`
- unable to read response from snode
- unexpected data type, e.g.
```
2021/09/09 07:41:26 Result from 03253fe64f398bcf7b6c9b6534fffb28e5892a6c9d3fa54dff86db158bcc68c565:
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    Body {
        Width: 35em;
        Margin: 0 auto;
        Font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
Working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href=http://nginx.org/>nginx.org</a>.<br/>
Commercial support is available at
<a href=http://nginx.com/>nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
```

**Comment by Akado2009** [comment]
https://github.com/blocknetdx/go-xrouter/pull/22
