### ISSUE TITLE
mostCommonReply should reflect only a majority view

### ISSUE THREAD

**Issue by synechist** [blocknetdx/go-xrouter#46]
If no majority view is returned from service nodes after Go-XRouter makes a request (e.g. `queryCount` of 2 and two different responses returned), then the resulting "consensus" response set should have no responses in `mostCommonReply`. 
Instead, there should be 2 `divergentReplies`.

**Comment by Akado2009** [comment]
https://github.com/blocknetdx/go-xrouter/commit/b2ff5bc5b654658b2645e3a7a72ae7cc80331cb7 and https://github.com/blocknetdx/go-xrouter/pull/22
